---
title: "Week 10 Exercises"
author: "Aaron Palumbo"
date: "October 27, 2015"
output: pdf_document
toc: yes
---

## 7.6.1 (Section 7.6.7)

Execute the BDMO Algorightm with $p = 3$ on the following 1-dimensional, Euclidean data:

$$1, 45, 80, 24, 56, 71, 17, 40, 66, 32, 48, 96, 9, 41, 75, 11, 58, 93, 28, 39, 77$$

The clustering algorithms is *k*-means with $k = 3$. Only the centroid of a cluster, along with its count, is needed to represent a cluster.


```{r, warning=FALSE, message=FALSE}
# Custom clustering library
source("clustering_library.R")

# Load in data
x <- c( 1,  45, 80, 24, 56, 71, 17, 
        40, 66, 32, 48, 96,  9, 41, 
        75, 11, 58, 93, 28, 39, 77)

records <- data.frame(x=x)

# Cluster parameters
p <- 3
k <- 3

# Break up data into buckets
buckets <- initBuckets(records, 3, 2)

bdmo <- lapply(buckets, function(b) {
  rec <- b[['records']]
  if (nrow(rec) > k) {
    km <- kmeans(rec, k)
    return(list(centroid = km$centers,
                count = length(km$cluster)))
  } else {
    return(list(centroid = rec,
                count = nrow(rec)))
  }
    
})

for (b in bdmo) {
  print("Centroid:")
  print(t(b[['centroid']]))
  print
  print(c("Count: ", b[['count']]))
  print("---------------------------")
}
  
```



## Appendix

Code for initBuckets

```{r code=capture.output(dump('initBuckets', ''))}

```
